config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart' # changed get to post
  post 'order_complete' => 'cart#order_complete'

  get 'view_order' => 'cart#view_order' # add custom url instead of cart/view_order
  get 'checkout' => 'cart#checkout'

  get 'items' => 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  devise_for :users
  resources :products

  root 'storefront#all_items'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!, except: [:add_to_cart, :view_order]

  def add_to_cart
    @order = current_order

    line_item = @order.line_items.new(product_id: params[:product_id], quantity: params[:quantity])
    @order.save
    session[:order_id] = @order.id

    line_item.update(line_item_total: (line_item.product.price * line_item.quantity))

    redirect_back(fallback_location: root_path)
  end

  def view_order
    @line_items = current_order.line_items
  end

  def checkout
    line_items = current_order.line_items

    if line_items.length != 0
      current_order.update(user_id: current_user.id, subtotal: 0)
      @order = current_order

      line_items.each do |line_item|
        line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))
        @order.order_items[line_item.product_id] = line_item.quantity
      @order.subtotal += line_item.line_item_total
      end

      @order.save

      @order.update(sales_tax: (@order.subtotal * 0.08))
      @order.update(grand_total: (@order.sales_tax + @order.subtotal))

      @order.line_items.destroy_all
      session[:order_id] = nil
    end
  end

  def order_complete
    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to cart_path
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<div class="container" style="font-family: Verdana, Geneva, sans-serif;">

  <h2>Thanks for shopping with us!</h2>
  <p>Let's review your order:</p>

  <table class="table table-striped table-hover table-bordered">
        <thead>
          <tr>
            <th>Item</th>
            <th>Qty</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_items.each do |key, value| %>
            <tr>
              <td><%= Product.find(key).name %></td>
              <td><%= value %></td>
            </tr>
          <% end %>
            <tr>
              <th colspan="1"><span class="pull-right">Sub Total</span></th>
              <td><%= number_to_currency(@order.subtotal) %></td>
            </tr>
            <tr>
              <th colspan="1"><span class="pull-right">Sales Tax</span></th>
              <td><%= number_to_currency(@order.sales_tax) %></td>
            </tr>
            <tr>
              <th colspan="1"><span class="pull-right">Grand Total</span></th>
              <td><%= number_to_currency(@order.grand_total) %></td>
            </tr>
  </table>

  <%= form_tag order_complete_path do %>
    <article>
      <label class="amount">
        <span><%= number_to_currency(@order.grand_total) %></span>
      </label>
    </article>
    <div>
      <%= hidden_field_tag :order_id, @order.id %>
    </div>
    <script src="https://checkout.stripe.com/checkout.js"
            class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Order #<%= @order.id %>"
            data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
  <% end %>
</div>

app/views/cart/order_complete.html.erb
<div class="container" style="font-family: Verdana, Geneva, sans-serif;">
  <h2>Thank you for your order!</h2>

  <p>
    Order #<%= @order.id %> will be shipping to you, <%= @order.user.name %>, as soon as possible!
  </p>

</div>

app/views/cart/view_order.html.erb
<div class="container" style="font-family: Verdana, Geneva, sans-serif;">

  <h1>Shopping Cart</h1>
  <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th>Item</th>
                <th>Qty</th>
                <th>Unit Price</th>
                <th>Total Price</th>
            </tr>
        </thead>
        <tbody>
            <% @line_items.each do |line_item| %>
                <tr>
                    <td><%= line_item.product.name %></td>
                    <td><%= line_item.quantity %></td>
                    <td><%= number_to_currency(line_item.product.price) %></td><td><%= number_to_currency(line_item.line_item_total) %></td>
                </tr>
            <% end %>
            <tr>
                <td><%= link_to "Continue Shopping", root_path, class: 'btn btn-primary' %></td>
                <td colspan="3"><%= link_to "Checkout", checkout_path, class: "pull-right btn btn-success" %></td>
            </tr>
        </tbody>
    </table>

</div>