config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart' # changed get to post
  post 'order_complete' => 'cart#order_complete'

  get 'view_order' => 'cart#view_order' # add custom url instead of cart/view_order
  get 'checkout' => 'cart#checkout'

  get 'items' => 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  devise_for :users
  resources :products

  root 'storefront#all_items'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
    @products = Product.all
  end

  def items_by_category
    @products = Product.where(category: params[:category_id])
    @category = Category.find(params[:category_id])
  end

  def items_by_brand
    @products = Product.where(brand: params[:brand])
    @brand = params[:brand]
  end
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/storefront/_productloop.html.erb
<% @products.each do |product| %>
  <div class="col-md-4 text-center">
    <div class="well center-it" style="height: 250px;">
      <p><%= image_tag product.image.url(:thumb) %></p>
      <h3><%= link_to product.name, product %></h3>
      <p><%= number_to_currency(product.price) %></p>
      <p>
        <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>" class="btn btn-info">
          <span class="glyphicon glyphicon-plus"></span> Quick Info
        </a>
      </p>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade text-center" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
<!--               <h4 class="modal-title" id="myModalLabel">Modal title</h4> -->
        </div>
        <div class="modal-body">
          <p><%= image_tag product.image.url(:medium), class: 'storefront-pics' %></p>
          <h3><%= link_to product.name, product %></h3>
          <p><%= number_to_currency(product.price) %></p>
          <p>made by <%= product.brand %></p>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button> -->
          <p>
            <%= form_tag add_to_cart_path do %>
              <%= hidden_field_tag :product_id, product.id %>
              <%= number_field_tag :quantity, 1, placeholder: "How many?" %>
              <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/storefront/all_items.html.erb
<%#= render 'layouts/main' %>
<div class="container" style="font-family: Verdana, Geneva, sans-serif;">
  <h1>Here are all our products:</h1>

  <div class="row">
    <%= render 'productloop' %>
  </div>

</div>

app/views/storefront/items_by_brand.html.erb
<div class="container" style="font-family: Verdana, Geneva, sans-serif;">
  <h1>Here are our <%= @brand %> products:</h1>

  <div class="row">
    <%= render 'productloop' %>
  </div>
</div>

app/views/storefront/items_by_category.html.erb
<div class="container" style="font-family: Verdana, Geneva, sans-serif;">
  <h1>All of our <%= @category.name %></h1>

  <div class="row">
    <%= render 'productloop' %>
  </div>
</div>