config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart' # changed get to post
  post 'order_complete' => 'cart#order_complete'

  get 'view_order' => 'cart#view_order' # add custom url instead of cart/view_order
  get 'checkout' => 'cart#checkout'

  get 'items' => 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  devise_for :users
  resources :products

  root 'storefront#all_items'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_main.html.erb
<div class="jumbotron">
  <div style="background-image: url('https://cdn.pixabay.com/photo/2016/09/16/19/19/online-store-1674907_960_720.png');
              background-repeat: no-repeat;
              background-size: cover;
              background-position: center;
              margin-top: -70px;
              margin-bottom: -70px;
              padding: 30%;">
    <h1 class="text-center" style="font-family: Verdana, Geneva, sans-serif;">Welcome to the YP Store!</h1>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<!-- <nav class="navbar navbar-default" style="margin-bottom: 0;"> -->
<nav class="navbar navbar-light" style="font-family: Verdana, Geneva, sans-serif; margin-bottom: 15px; background-color: #e3f2fd;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

<!--       <a class="navbar-brand" href="#">
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/77/YP_icon.png" width="30" height="30">
      </a>
 -->
       <a class="navbar-brand" href="#">
        <%= link_to root_path do %>
        <!-- <%#= image_tag("YP_icon.png", size: "40") %> -->
        <%= image_tag("online-store.png", size: "50") %>
        <% end %>
      </a>

    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "Backroom", products_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @categories.each do |category| %>
                <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
              <% end %>
              <li><%= link_to 'All', root_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @brands.each do |brand| %>
                <li><%= link_to brand, branding_path(brand: brand) %></li>
              <% end %>
              <li><%= link_to 'All', root_path %></li>
            </ul>
          </li>
          <% if can? :create, Product %>
            <li><%= link_to "New Product", new_product_path %></li>
          <% end %>
        <% else %>
          <li><p class="navbar-text">Welcome to the YP Store!</p></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right" style="margin-right: 10px;">
        <% if current_user %>
          <li><p class="navbar-text">Welcome back, <%= current_user.name %>!</p></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-outline-primary' %></li>
          <li><%= link_to "Log In", new_user_session_path, class: 'btn btn-outline-secondary' %></li>
        <% end %>
        <% if LineItem.count != 0 %>
          <li><button class="btn btn-info navbar-btn" type="button"><span class="glyphicon glyphicon-shopping-cart"></span> <%= link_to LineItem.count, view_order_path %> <span class="badge"></span></button></li>
        <% else %>
          <li><button class="btn btn-info navbar-btn" type="button"><span class="glyphicon glyphicon-shopping-cart"></span> <%= link_to "", view_order_path %></button></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>